### ISSUE TITLE
Maintaining a linux Kernel source?

### ISSUE THREAD

**Issue by piggy181** [faux123/Shamu#1]
Hi, 
My question may not be what you expect. But it's intriguing and thus I hope you give me some ideas.
Could you give me some clues as to why you spend effort to maintain a linux kernel source code? Isn't it possible to get the latest Kernel source code from an authoritative source such as kernel.org?

/py181

**Comment by faux123** [comment]
Unfortunately no.  Android has many customization added on top of standard linux kernel and also ARM processors have very specific architecture specific patches on top as well.  Both Google and Linux have been working together to merge the two.  May be in a few more years or so we can just use 1 unified kernel from kernel.org.

Hope this helps.
